In [1]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np
a=np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])
a

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [3]:
import numpy as np
a=np.array([[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6]])
a[2]

array([1, 2, 3, 4, 5, 6])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [15]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])