In [1]:
import numpy as np

## Creating 1 dimensional array

In [2]:
a1D = np.array([1, 2, 3, 4])
a1D


array([1, 2, 3, 4])

## Creating 2 dimensional array

In [4]:
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

## Creating 3 dimensional array

In [3]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3D


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])